---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: quay-postgres-storage
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 10Gi
    storageClassName: managed-premium
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quay-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: quay-postgres
    spec:
      containers:
      - name: quay-postgres
        image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1-35
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "admin"
        - name: POSTGRESQL_DATABASE
          value: "quay"
        - name: POSTGRESQL_PASSWORD
          value: "!Passw0rd1234"
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: quay-postgredb
        serviceAccount: postgres
        serviceAccountName: postgres
      volumes:
      - name: quay-postgredb
        persistentVolumeClaim:
          claimName: quay-postgres-storage
---
apiVersion: v1
kind: Service
metadata:
  name: quay-postgres
  labels:
    app: quay-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: quay-postgres
