---
apiVersion: v1
kind: Service
metadata:
  namespace: quay-enterprise
  name: quay-svc-clusterip
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 8443
  selector:
    quay-enterprise-component: app

---
apiVersion: v1
kind: Route
metadata:
  name: quay
  namespace: quay-enterprise
spec:
  to:
    kind: Service
    name: quay-svc-clusterip
  tls:
    termination: passthrough

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: quay-enterprise
  name: quay
  labels:
    quay-enterprise-component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-enterprise-component: app
  template:
    metadata:
      namespace: quay-enterprise
      labels:
        quay-enterprise-component: app
    spec:
      volumes:
        - name: configvolume
          secret:
            secretName: quay-config-secret
      containers:
      - name: quay-enterprise-app
        image: quay.io/redhat/quay:v3.2.1
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: configvolume
          readOnly: false
          mountPath: /conf/stack
        env:
        - name: DEBUGLOG
          value: "true"
        - name: QE_K8S_CONFIG_SECRET
          value: "quay-config-secret"
      imagePullSecrets:
        - name: redhat-pull-secret
