apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quay-postgres
  namespace: quay-enterprise
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: quay-postgres
    spec:
      containers:
      - name: quay-postgres
        image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1-35
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "admin"
        - name: POSTGRESQL_DATABASE
          value: "quay"
        - name: POSTGRESQL_PASSWORD
          value: "!Passw0rd1234"
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: quay-postgredb
        serviceAccount: postgres
        serviceAccountName: postgres
      volumes:
      - name: quay-postgredb
        persistentVolumeClaim:
          claimName: quay-postgres-storage
