apiVersion: v1
kind: Service
metadata:
  name: quay-postgres
  namespace: quay-enterprise
  labels:
    app: quay-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: quay-postgres
